plugins {
	id 'java'
	id 'eclipse'
}

repositories {
	mavenCentral()
}

sourceSets {
	main {
		java { srcDirs = ['src'] }
	}
	test {
		java { srcDirs = ['test'] }
	}
}

dependencies {
	testImplementation 'junit:junit:4.13.2'
}

task getDependencies(type : Copy) {
	from configurations.testRuntimeClasspath
	into 'lib'
}

eclipse {
	classpath {
		plusConfigurations += [configurations.testRuntimeClasspath]
		defaultOutputDir = file('build-eclipse')
	}
}

task setupProject {
	dependsOn getDependencies, eclipseClasspath
}